parameters:
  cottages_csv_path: '%kernel.project_dir%/var/data/cottages.csv'
  bookings_csv_path: '%kernel.project_dir%/var/data/bookings.csv'

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # Makes classes in src/ available as services (with their fully-qualified class names)
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # Custom service definitions
  App\Service\CottageCsvService:
    arguments:
      $csvPath: '%cottages_csv_path%'

  App\Service\BookingCsvService:
    arguments:
      $csvPath: '%bookings_csv_path%'
